Chris mon 02 06 17
ghseeli/grad-school-notes pull request #9
Opened 2017-02-06 17:55 UTC by cjl8zf

2017-02-06 23:13 UTC, cjl8zf commented
Hey @MareoRaft I added you as a reviewer for this week

2017-02-11 22:20 UTC, MareoRaft commented
@cjl8zf For mathematical changes, do you prefer for me to make comments, or make the changes directly to the file?

2017-02-12 04:15 UTC, MareoRaft commented on Algebraic Topology/algebraic-topology.tex
> +structure under the gluing map \(S^{n} \to \R P^{n-1}\) where
Maybe he meant S^{n-1}?  The picture that I do understand in my mind is the representation of RP^2 (lines in R3) as a CW complex.  It looks like a disk D2 with half the circumference identified with the other half of the circumference.

In that particular case, what would the glueing map be?  Would it be glueing the two circumference halves (S^1) to itself?

2017-02-12 04:25 UTC, MareoRaft commented on Algebraic Topology/algebraic-topology.tex
> +  open in \(X\) if and only if \(q^{-1}(X)\) is open, where \(q\) is
I think he meant q^{-1}(\mathcal{O}).

2017-02-12 04:39 UTC, MareoRaft commented on Algebraic Topology/algebraic-topology.tex
> +  topology through the quotient topology, that is, \(\mathcal{O}\) is
They do? Can you give an example?  What is the quotient map in this case?

2017-02-12 04:53 UTC, MareoRaft requested changes
This is good Chris.  I feel like I'm *this* close to understanding CW-complexes!  Or should I say, CW-complices?

There were some comments I made that weren't included as part of "the review".  But you should still be able to see them under the "files changed" tab.

2017-02-12 04:53 UTC, MareoRaft commented on Algebraic Topology/algebraic-topology.tex
> +  X_2 &= D_2
Maybe he meant D^2 ?  I still don't get CW-complexes.  For the torus, X_0 and X_1 make sense, but this X_2 does not make sense to me.  Do we eventually get the torus itself (S^1 \x S^1) for one of the X_n's ?

2017-02-12 04:53 UTC, MareoRaft commented on Algebraic Topology/algebraic-topology.tex
> +  X_2 &= D_2
Or maybe he meant T^2

2017-02-12 14:45 UTC, MareoRaft commented
Or rather, the comments are hidden in the "Show outdated" links on this page.

2017-02-17 13:39 UTC, cjl8zf commented on Algebraic Topology/algebraic-topology.tex
> +  X_2 &= D_2
what I was trying to say was that you glue on a single 2-cell, not sure the correct notation, any suggestions?

2017-02-17 18:46 UTC, MareoRaft commented on Algebraic Topology/algebraic-topology.tex
> +  X_2 &= D_2
I understand CW complexes better now.  So the result of gluing on a single 2-cell is that you do in fact receive the torus as X2.  So X_2 &= M_1, the torus.

2017-02-17 18:52 UTC, merged

2017-02-17 18:52 UTC, MareoRaft commented
I merged this but you can still comment / review if you want.